# @baseUrl = http://localhost:7081
@baseUrl = https://weatherstation-m2xzi7kvvmqeq.azurewebsites.net
@apiKey = securesecretkey
@jobId = 679f167c-9713-47dc-8703-b0970297de75

### Create Images Job
GET {{baseUrl}}/api/CreateImages
X-API-Key: {{apiKey}}

### Get Generated Images (Replace {jobId} with actual job ID from previous response)
GET {{baseUrl}}/api/images/{{jobId}}
X-API-Key: {{apiKey}}